[package]
name = "openmove"
version = "1.0.0"
authors = ["Gavin Fu <gavfu@outlook.com>"]

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
openmove = '_'

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/move-stdlib"
rev = "main"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-stdlib"
rev = "main"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = "main"